In [58]:
import pandas as pd

df = pd.read_csv('ca212fb975d63bfff9687874de60bd2f67cbf06c44558-job-profiles.csv')

df.columns

Index(['Team ID', 'Team Name', 'User Type', 'Name', 'Email', 'Mobile',
       'Gender', 'Country', 'Differently Abled', 'Course Duration (years)',
       'Course Programme', 'Course Pursuing', 'Course Specialization',
       'Course Stream', 'Organisation Name', 'Others', 'Passing Out Year',
       'Year Of Study', 'Work Experience', 'Score', 'Status',
       'Report page URL'],
      dtype='object')

In [59]:
df_female = df[df['Gender'] == 'F']
len(df_female)

df = df_female

32

In [60]:
sorted_df = df.sort_values(by='Score', ascending=False)
sorted_df = sorted_df[['Name', 'Email', 'Mobile', 'Score']]
len(sorted_df)
sorted_df

32

                     Name                           Email        Mobile  Score
3               PRIYA RAJ  23f2005039@ds.study.iitm.ac.in  919472439782  26.00
2                Ananya D  23f3004494@ds.study.iitm.ac.in  919392231162  26.00
4                  Himani  24f2001069@ds.study.iitm.ac.in  917508800372  26.00
0       Shreya Bessupally  23f2005267@ds.study.iitm.ac.in  917075235528  24.75
29  Thiagarajan MEENAKSHI  23f3002817@ds.study.iitm.ac.in  916379216244  23.75
34        NITHYASHREE D N  24f3001893@ds.study.iitm.ac.in  919019723527  23.75
1          SNEHA Kulkarni  22f3001889@ds.study.iitm.ac.in  919972184488  22.75
31              SRIDEVI C  22f2000594@ds.study.iitm.ac.in  919249858301  22.75
18    Archisha Srivastava  23f3000114@ds.study.iitm.ac.in  918960608880  22.50
30        Utpreksha Singh  24f3001732@ds.study.iitm.ac.in  916263912116  22.50
20      Dibya Swarupa Das           b223017@iiit-bh.ac.in  918249063433  22.00
5           Aanchal Dixit  24f2008460@ds.study.iitm.ac.in  919616299519  21.50
7                Bhadra D           bhadra10a30@gmail.com  919895371065  20.75
12          SYLENE Bansal  22f3000419@ds.study.iitm.ac.in  917669967479  20.75
11           SHRUTI SINHA  22f3003063@ds.study.iitm.ac.in  917903864686  20.50
26            F DHANSHREE  24f3003220@ds.study.iitm.ac.in  919284198023  20.50
32          Aditi Paliwal  24f1000630@ds.study.iitm.ac.in  919977255069  20.50
28          Karnika Singh  24f2100374@es.study.iitm.ac.in  918957740379  19.50
22            Parul Gupta  24f2005002@ds.study.iitm.ac.in  919686775692  18.75
23               P TRISHA  23f1000097@ds.study.iitm.ac.in  917826043747  18.50
13           ANJALI DOGRA  22f3001285@ds.study.iitm.ac.in  919999306403  18.50
17        Akshitha Bhukya  25f1000208@ds.study.iitm.ac.in  919014740261  17.75
10                 DEVI S  23f3004196@ds.study.iitm.ac.in  919388282400  17.00
16              F KHADIJA  24f3001446@ds.study.iitm.ac.in  919346666132  16.75
15           Namrata sahu  25f1000718@ds.study.iitm.ac.in  919893386908  16.50
24            Antra Gupta  24f2006748@ds.study.iitm.ac.in  919415919905  14.25
19         Bhavya Basotia  23f3000095@es.study.iitm.ac.in  917878434435  13.50
27           Sanchari Bag       sancharibag0615@gmail.com  916290868830  11.00
9            JYOTI SHARMA  24f3001449@ds.study.iitm.ac.in  919137504723   0.00
8            Amisha Yadav      amishaayadav0108@gmail.com  919110074413   0.00
25   Dhanalakshmi Muttada          manvitha1729@gmail.com  919550191709   0.00
33      Charishma Kandepu    charishmakandepu27@gmail.com  919989119944   0.00

In [61]:
filtered_df = sorted_df[sorted_df['Email'].str.endswith('@ds.study.iitm.ac.in')]
len(filtered_df)
filtered_df

24

                     Name                           Email        Mobile  Score
3               PRIYA RAJ  23f2005039@ds.study.iitm.ac.in  919472439782  26.00
2                Ananya D  23f3004494@ds.study.iitm.ac.in  919392231162  26.00
4                  Himani  24f2001069@ds.study.iitm.ac.in  917508800372  26.00
0       Shreya Bessupally  23f2005267@ds.study.iitm.ac.in  917075235528  24.75
29  Thiagarajan MEENAKSHI  23f3002817@ds.study.iitm.ac.in  916379216244  23.75
34        NITHYASHREE D N  24f3001893@ds.study.iitm.ac.in  919019723527  23.75
1          SNEHA Kulkarni  22f3001889@ds.study.iitm.ac.in  919972184488  22.75
31              SRIDEVI C  22f2000594@ds.study.iitm.ac.in  919249858301  22.75
18    Archisha Srivastava  23f3000114@ds.study.iitm.ac.in  918960608880  22.50
30        Utpreksha Singh  24f3001732@ds.study.iitm.ac.in  916263912116  22.50
5           Aanchal Dixit  24f2008460@ds.study.iitm.ac.in  919616299519  21.50
12          SYLENE Bansal  22f3000419@ds.study.iitm.ac.in  917669967479  20.75
11           SHRUTI SINHA  22f3003063@ds.study.iitm.ac.in  917903864686  20.50
26            F DHANSHREE  24f3003220@ds.study.iitm.ac.in  919284198023  20.50
32          Aditi Paliwal  24f1000630@ds.study.iitm.ac.in  919977255069  20.50
22            Parul Gupta  24f2005002@ds.study.iitm.ac.in  919686775692  18.75
23               P TRISHA  23f1000097@ds.study.iitm.ac.in  917826043747  18.50
13           ANJALI DOGRA  22f3001285@ds.study.iitm.ac.in  919999306403  18.50
17        Akshitha Bhukya  25f1000208@ds.study.iitm.ac.in  919014740261  17.75
10                 DEVI S  23f3004196@ds.study.iitm.ac.in  919388282400  17.00
16              F KHADIJA  24f3001446@ds.study.iitm.ac.in  919346666132  16.75
15           Namrata sahu  25f1000718@ds.study.iitm.ac.in  919893386908  16.50
24            Antra Gupta  24f2006748@ds.study.iitm.ac.in  919415919905  14.25
9            JYOTI SHARMA  24f3001449@ds.study.iitm.ac.in  919137504723   0.00

In [62]:
g_form_emails = pd.read_csv('stree_sakti_quiz_participants.csv')
g_form_emails = list(g_form_emails['Email Address'])
g_form_emails[:5]

['24f3004596@ds.study.iitm.ac.in',
 '24f3001446@ds.study.iitm.ac.in',
 '23f3000095@es.study.iitm.ac.in',
 '23f3001151@ds.study.iitm.ac.in',
 '23f3000797@ds.study.iitm.ac.in']

In [63]:
not_in_g_form_df = filtered_df[~filtered_df['Email'].isin(g_form_emails)]
not_in_g_form_df

              Name                           Email        Mobile  Score
2         Ananya D  23f3004494@ds.study.iitm.ac.in  919392231162  26.00
1   SNEHA Kulkarni  22f3001889@ds.study.iitm.ac.in  919972184488  22.75
31       SRIDEVI C  22f2000594@ds.study.iitm.ac.in  919249858301  22.75
22     Parul Gupta  24f2005002@ds.study.iitm.ac.in  919686775692  18.75
9     JYOTI SHARMA  24f3001449@ds.study.iitm.ac.in  919137504723   0.00

In [ ]:
not_in_g_form_df.to_csv('not_in_g_form_df.csv')

In [64]:
filtered_g_form_df = filtered_df[filtered_df['Email'].isin(g_form_emails)]
len(filtered_g_form_df)
filtered_g_form_df

19

                     Name                           Email        Mobile  Score
3               PRIYA RAJ  23f2005039@ds.study.iitm.ac.in  919472439782  26.00
4                  Himani  24f2001069@ds.study.iitm.ac.in  917508800372  26.00
0       Shreya Bessupally  23f2005267@ds.study.iitm.ac.in  917075235528  24.75
29  Thiagarajan MEENAKSHI  23f3002817@ds.study.iitm.ac.in  916379216244  23.75
34        NITHYASHREE D N  24f3001893@ds.study.iitm.ac.in  919019723527  23.75
18    Archisha Srivastava  23f3000114@ds.study.iitm.ac.in  918960608880  22.50
30        Utpreksha Singh  24f3001732@ds.study.iitm.ac.in  916263912116  22.50
5           Aanchal Dixit  24f2008460@ds.study.iitm.ac.in  919616299519  21.50
12          SYLENE Bansal  22f3000419@ds.study.iitm.ac.in  917669967479  20.75
11           SHRUTI SINHA  22f3003063@ds.study.iitm.ac.in  917903864686  20.50
26            F DHANSHREE  24f3003220@ds.study.iitm.ac.in  919284198023  20.50
32          Aditi Paliwal  24f1000630@ds.study.iitm.ac.in  919977255069  20.50
23               P TRISHA  23f1000097@ds.study.iitm.ac.in  917826043747  18.50
13           ANJALI DOGRA  22f3001285@ds.study.iitm.ac.in  919999306403  18.50
17        Akshitha Bhukya  25f1000208@ds.study.iitm.ac.in  919014740261  17.75
10                 DEVI S  23f3004196@ds.study.iitm.ac.in  919388282400  17.00
16              F KHADIJA  24f3001446@ds.study.iitm.ac.in  919346666132  16.75
15           Namrata sahu  25f1000718@ds.study.iitm.ac.in  919893386908  16.50
24            Antra Gupta  24f2006748@ds.study.iitm.ac.in  919415919905  14.25

In [65]:
top_10 = filtered_g_form_df.nlargest(10, 'Score')
top_10

top_10.to_csv('top_10.csv', index=False)

                     Name                           Email        Mobile  Score
3               PRIYA RAJ  23f2005039@ds.study.iitm.ac.in  919472439782  26.00
4                  Himani  24f2001069@ds.study.iitm.ac.in  917508800372  26.00
0       Shreya Bessupally  23f2005267@ds.study.iitm.ac.in  917075235528  24.75
29  Thiagarajan MEENAKSHI  23f3002817@ds.study.iitm.ac.in  916379216244  23.75
34        NITHYASHREE D N  24f3001893@ds.study.iitm.ac.in  919019723527  23.75
18    Archisha Srivastava  23f3000114@ds.study.iitm.ac.in  918960608880  22.50
30        Utpreksha Singh  24f3001732@ds.study.iitm.ac.in  916263912116  22.50
5           Aanchal Dixit  24f2008460@ds.study.iitm.ac.in  919616299519  21.50
12          SYLENE Bansal  22f3000419@ds.study.iitm.ac.in  917669967479  20.75
11           SHRUTI SINHA  22f3003063@ds.study.iitm.ac.in  917903864686  20.50

In [66]:
top_10_emails = top_10[['Email']]
top_10_emails.to_csv('top_10_emails.csv', index=False)